### ISSUE TITLE
gravatar link

### ISSUE THREAD

**Issue by hamedrnik** [jnaqsh/nerdnews#11]
create a link on avatar to link gravatar.com

**Comment by arashm** [comment]
I can't understand this one. Why linking to Gravatar? there's no way to change avatar picture in Gravatar website. Avatars can only be changed from their e-mail provider profile I suppose.

**Comment by hamedrnik** [comment]
That's simple, when we provide a link everyone can be notified that we use Gravatar for avatar.
You can go into your github profile for an example: https://github.com/settings/profile

**Comment by arashm** [comment]
hmmm... Never seen such thing on any other sites. Did you see? It doesn't seem logical to me.

**Comment by hamedrnik** [comment]
It seems that you couldn't read previous comment carefully. Github, Stackoverflow, Wordpress are examples that I used.

**Comment by arashm** [comment]
fine. got that.
