### ISSUE TITLE
Removing the "Dislike" Buton

### ISSUE THREAD

**Issue by amrza** [jnaqsh/nerdnews#15]
the "dislike" button could be use by some users (haters) to abuse other users and their opinion. (this is happening everyday in reddit, narenji, ....)

if you like something, push the "like" button and share your positive feelings.
BUT if you dont like it, well... just ignore it! (like facebook)

hamed tells me the "dislike" button is usefull for specifying "spam posts". well, i dont see that case, because every incoming post will be reviewed.

**Comment by hamedrnik** [comment]
We will removed review action in next version, so I think dislike button that could be good for spamers

**Comment by hamedrnik** [comment]
After about three months, I think it could be good to remove dislike button and instead we have to prepare an abuse or spam button for spammers.
Anyway, thanks for your good suggestion.

**Comment by amrza** [comment]
if you want to do so, its a good idea to make the "like" button a little bit bigger (in pixel size)... anyway, i think its time to close this issue :)

**Comment by hamedrnik** [comment]
It could be better close the issue after fixing the problem.

**Comment by arashm** [comment]
Speaking of voting buttons, I think the multiple options for voting is deprecated these days. We can't make enough options to show users feelings.
I think what G+ does is nicer, simpler and easier for users.

**Comment by hamedrnik** [comment]
@arashm It's better to not conclude the final decision about voting. Could your revert it to the base implementation?
