### ISSUE TITLE
comment supports markdown markup

### ISSUE THREAD

**Issue by bijanebrahimi** [jnaqsh/nerdnews#16]
for a better view and better readability, it would be better to have markdown or any lightweight markup language to enrich the comment :)

**Comment by hamedrnik** [comment]
Thanks for your suggestion, so we will add Textile language for comments

**Comment by hamedrnik** [comment]
this is done by https://github.com/jnaqsh/nerdnews/commit/e1565b537534c7c365fd453271dddcf86656f56b
