### ISSUE TITLE
No way to view/edit a submitted post

### ISSUE THREAD

**Issue by mtux** [jnaqsh/nerdnews#19]
After submitting a news, while it waits for acceptance from admins, there's no way to view or edit submitted post. it just vanished!
I suggest you add it somewhere in my profile. so I can know about it's existence and even what happened to it (if it rejected/accepted)

**Comment by mtux** [comment]
Now I can see an option to see "unpublished news" (after my previous post published by admin)

**Comment by hamedrnik** [comment]
Good suggestion. In next version, we will removed acceptance from admins. So everyone can submit a story without acceptance.

**Comment by hamedrnik** [comment]
it's done by https://github.com/jnaqsh/nerdnews/commit/c415f3661720d36dea9cceb4b10e5de15155f504
