### ISSUE TITLE
Valid URL Checking

### ISSUE THREAD

**Issue by bijanebrahimi** [jnaqsh/nerdnews#27]
NerdNews should check for Valid URL Request Response before posting the story. obviously post stories only, if the referenced link has HTTP Response 200.

**Comment by arashm** [comment]
I implemented this once but Hamed decided to remove it due to it's pressure on server

**Comment by hamedrnik** [comment]
Actually it's not about pressure on the server, It's about the time it takes for checking and this might be annoying.

**Comment by arashm** [comment]
Oh yes, sorry. You mentioned that.
