### ISSUE TITLE
Persian characters in URL

### ISSUE THREAD

**Issue by danialbehzadi** [jnaqsh/nerdnews#29]
Existence of Persian characters in URL, not only make it difficult to link the stories, but even makes the link doesn't work at all in some websites like twitter, so the sharing button is uselesss.
I think it is a good idea to map Persian characters with English one, Generate a URL for stories by the time and time of creation or some thing like that and not the title, or in the "!gsh"est way, convert the URL by a URL shortener before sharing on twitter

**Comment by hamedrnik** [comment]
It might be a problem for sharing social network but it has advantage for search engine optimization, also we are iranian and we must speak in persian.
I think it could be good, every story has its own shortener URL and this is good for sharing social network.
