### ISSUE TITLE
Font in windows

### ISSUE THREAD

**Issue by jaavid** [jnaqsh/nerdnews#30]
این فونت توی ویندوز به خوبی نمایش داده نمیشود.
اینجا را ببینید 
http://writeweb.ir/1390/03/iraniansans-gooder-style/

**Comment by hamedrnik** [comment]
فونت iranian sanz برای کاربران ویندوز اضافه گردید.
Thanks
adds by commit https://github.com/jnaqsh/nerdnews/commit/b5ae5db20db932fda34832fd0b78014e34366fc1
