### ISSUE TITLE
Windows can't load icon-star or ... which is after <span class="tag_id_** ">

### ISSUE THREAD

**Issue by rayeshman** [jnaqsh/nerdnews#31]
In windows I can't see star icon or ...
in:
<i class='icon-star'>
<i class='icon-user'>

**Comment by hamedrnik** [comment]
@rayeshman  Could you tell what your Browser/Version is?

**Comment by rayeshman** [comment]
It has been solved on my Windows!
and I don't know what version of Firefox I had.
