### ISSUE TITLE
RSS feeds should point out to real referenced link, not the nerdnews

### ISSUE THREAD

**Issue by bijanebrahimi** [jnaqsh/nerdnews#37]
when the full story is available on RSS feed, why should it be pointing to the same story?

i know it's good for leaving comments BUT the real referenced link should be available in RSS feed as well [maybe as a link at the bottom of the story at least].

**Comment by hamedrnik** [comment]
It will be implemented in next version and a link to reference url will be in the RSS feed. Thanks.
