### ISSUE TITLE
دیدگاه ها

### ISSUE THREAD

**Issue by vahit** [jnaqsh/nerdnews#4]
سلام خسته نباشید بچه ها :)
در مورد بخش دیدگاه‌ها دو تا مسئله هست.
اوّل اینکه برای خبر «انتشار رسمی Valve برای لینوکس» نشون می ده یک دیدگاه وجود داره ولی چیزی نشون نمیده و در زیر می نویسه «هیچ دیدگاهی وجود ندارد. »
دوّم اینکه می خواستم نظری ارسال کنم (برای همین خبر) ولی با خطای :
We're sorry, but something went wrong.
مواجه شدم.
البته نه ثبت نام کردم و نه وارد شدم !!

**Comment by hamedrnik** [comment]
سلام
فکر می‌کنم مشکل در استفاده از popstate باشه که در مرورگر کروم باید یکم تغییر کنه
فعلا popstate رو برداشتم تا ببنینم مشکل از چیه؟
ممنون بابت اطلاع‌رسانی
