### ISSUE TITLE
Voting Twice!

### ISSUE THREAD

**Issue by aidin36** [jnaqsh/nerdnews#40]
User can vote twice in this special situation:

I pressed the Green Vote Button once, and select one of the options.
Then, my browser started to load. It took a little while.
Before it loads the page again, I pressed the green button again and select another option.

Now two votes are registered!

Take a look at this [link](http://nerdnews.ir/stories/%D8%AC%D8%A7%DB%8C%D8%B2%D9%87-%D8%A8%DB%8C%D9%84-%DA%AF%DB%8C%D8%AA%D8%B3-%D8%A8%D8%B1%D8%A7%DB%8C-%D8%AA%D9%88%D8%B3%D8%B9%D9%87-%D9%88-%D8%A7%D8%A8%D8%AF%D8%A7%D8%B9-%DA%A9%D8%A7%D9%86%D8%AF%D9%88%D9%85%E2%80%8C%D9%87%D8%A7%DB%8C-%D8%A8%D9%87%D8%AA%D8%B1), and see that I voted twice under the "آیدین غریب‌نواز" ID.

It's better not to rely on the UI (Disabled vote buttons). Server should check for duplication individually.

**Comment by hamedrnik** [comment]
I knew it before, after a ajax request, buttons must be disabled and also a validation of uniqueness on votes will be created.
This will be fixed in the next version of nerdnews.
Thanks for your reporting
