### ISSUE TITLE
new blank line

### ISSUE THREAD

**Issue by amad** [jnaqsh/nerdnews#72]
It will be nice to have ability to create blank line in nerdnews markdown like text formating ..
better typo and better reading experience indeed.

the concept may be double space or tab in empty line like markdown standard.

as I'm not ruby programmer I can't help or contribute to this project and I have to submit simple issue request instead of pull request.

**Comment by hamedrnik** [comment]
@Stunt Hi Ahmad, I appreciated your participate in the NerdNews project.
We use Textile Format for our text. There is a quick tutorial for learning Textile: http://redcloth.org/hobix.com/textile/ 
Ahmad, @arashm and I are working on the next version of the NerdNews which has lots of new things, majority of them will be UI improvement.
Thanks for your helping the NerdNews project :)

**Comment by arashm** [comment]
@Stunt https://github.com/Stunt Hey Ahmad, you mean the horizontal space
between paragraphs? Now that you said I think we need a little space
between them.

**Comment by amad** [comment]
@iCEAGE, your welcome

@arashm, yes commonly in long text it seems is not exquisite for reader.

unfortunately I failed to find this option in Textile's markup manual and it seems is not supported. may it needs some hacks from someone to this component or just carefully a little css adjustment for temporary fix.
indeed paragraphs need space in between for more readability.

The best practices is let users to control it with markup. IMO :D

**Comment by arashm** [comment]
If we add an empty line between each paragraph, RedCloth will put each of them in a `<p>` tag. I just [added](e6537cb3b90032d9475102e0e8c45b5be50cd81d) a margin of 10px for each of them and every thing should look ok now.

I close the issue.
