### ISSUE TITLE
Broken link in FAQ page

### ISSUE THREAD

**Issue by farooqkz** [jnaqsh/nerdnews#78]
the last question(چه کسی آنرا هاست میکند؟) has a broken link(سرور شرکت نقش)

**Comment by arashm** [comment]
Thank you. The company, JNaqsh has been long gone since the owners are now left the country. The project is also not being actively developed.

**Comment by farooqkz** [comment]
"the project" refers to nerdnews' system?
They can simply buy this domain again.

**Comment by arashm** [comment]
Yes, I meant NerdNews  by "the project".

**Comment by farooqkz** [comment]
Ok, You may close this. but a good Free project may never die.
